CREATE DATABASE IF NOT EXISTS cuadernotutorfct;

USE cuadernotutorfct;

CREATE TABLE TUTOR_DOCENTE (
    DNI VARCHAR(10) PRIMARY KEY NOT NULL,
    Apellido_1 VARCHAR(50) NOT NULL,
    Apellido_2 VARCHAR(50) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE EMPRESA (
    CIF VARCHAR(20) PRIMARY KEY NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Domicilio_social VARCHAR(100) NOT NULL,
    Poblacion VARCHAR(50) NOT NULL,
    Codigo_postal VARCHAR(10) NOT NULL,
    Provincia VARCHAR(50) NOT NULL,
    Telefono VARCHAR(20) NOT NULL,
    Fax VARCHAR(20),
    Movil VARCHAR(20),
    Titularidad VARCHAR(50) NOT NULL,
    Actividad VARCHAR(100) NOT NULL,
    NIF_representante_legal VARCHAR(20) NOT NULL,
    Nombre_representante_legal VARCHAR(100) NOT NULL,
    Cargo_representante_legal VARCHAR(50) NOT NULL,
    Horario_apertura TIME,
    Horario_cierre TIME,
    Observaciones VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ALUMNO (
    DNI VARCHAR(10) PRIMARY KEY NOT NULL,
    Apellidos VARCHAR(50) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Domicilio VARCHAR(50) NOT NULL,
    Población VARCHAR(50) NOT NULL,
    Codigo_postal VARCHAR(10) NOT NULL,
    Provincia VARCHAR(50) NOT NULL,
    Fecha_nacimiento DATE NOT NULL,
    Edad INT NOT NULL,
    Teléfono VARCHAR(20) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Género VARCHAR(1) NOT NULL,
    Nombre_padre VARCHAR(50) NOT NULL,
    Observaciones VARCHAR(100),
    Tipo_empresa_FCT VARCHAR(50),
    Solicita_beca BOOLEAN NOT NULL,
    Cuenta_bancaria VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CENTRO_TRABAJO (
    id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Denominacion VARCHAR(100) NOT NULL,
    Domicilio VARCHAR(100) NOT NULL,
    Poblacion VARCHAR(50) NOT NULL,
    Codigo_postal VARCHAR(10) NOT NULL,
    Provincia VARCHAR(50) NOT NULL,
    Distancia INT NOT NULL,
    Preferencias_alumnado VARCHAR(500),
    CIF_EMPRESA VARCHAR(10) NOT NULL,
    FOREIGN KEY (CIF_EMPRESA) REFERENCES EMPRESA(CIF),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TUTOR_LABORAL (
    DNI VARCHAR(10) PRIMARY KEY NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Apellidos VARCHAR(50) NOT NULL,
    id_centro int(11) NOT NULL,
    CIF_EMPRESA VARCHAR(10) NOT NULL,
    FOREIGN KEY (id_centro) REFERENCES CENTRO_TRABAJO(id),
    FOREIGN KEY (CIF_EMPRESA) REFERENCES EMPRESA(CIF),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CUADERNO_TUTOR (
    Id_cuaderno INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    trimestre INT NOT NULL,
    ciclo_formativo_curso_actual VARCHAR(20) NOT NULL,
    plan_formativo VARBINARY(2000),
    CIF_EMPRESA VARCHAR(10) NOT NULL,
    DNI_tutor_docente VARCHAR(10) NOT NULL,
    visitas_previstas INT(2) NOT NULL,
    FOREIGN KEY (CIF_EMPRESA) REFERENCES EMPRESA(CIF),
    FOREIGN KEY (DNI_tutor_docente) REFERENCES TUTOR_DOCENTE(DNI),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CUESTIONARIO_EMPRESA (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    opcion_1 INT NOT NULL,
    opcion_2 INT NOT NULL,
    opcion_3 INT NOT NULL,
    opcion_4 INT NOT NULL,
    opcion_5 INT NOT NULL,
    opcion_6 INT NOT NULL,
    sugerencias VARCHAR(500),
    Id_cuaderno INT NOT NULL,
    dni_alumno VARCHAR(10) NOT NULL,
    FOREIGN KEY (Id_cuaderno) REFERENCES CUADERNO_TUTOR(Id_cuaderno),
    FOREIGN KEY (dni_alumno) REFERENCES ALUMNO(DNI),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE VALORACION_FINAL_TUTOR_DOCENTE (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    opcion_1 INT NOT NULL,
    opcion_2 INT NOT NULL,
    opcion_3 INT NOT NULL,
    opcion_4 INT NOT NULL,
    opcion_5 INT NOT NULL,
    opcion_6 INT NOT NULL,
    opcion_7 INT NOT NULL,
    opcion_8 INT NOT NULL,
    aspectos_destacables VARCHAR(100),
    evaluacion_final BOOLEAN NOT NULL,
    aspectos_mejorables VARCHAR(100),
    Id_cuaderno INT NOT NULL,
    dni_alumno VARCHAR(10) NOT NULL,
    FOREIGN KEY (dni_alumno) REFERENCES ALUMNO(DNI),
    FOREIGN KEY (Id_cuaderno) REFERENCES CUADERNO_TUTOR(Id_cuaderno),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE VALORACION_FINAL_TUTOR_LABORAL (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    opcion_1 INT NOT NULL,
    opcion_2 INT NOT NULL,
    opcion_3 INT NOT NULL,
    opcion_4 INT NOT NULL,
    opcion_5 INT,
    opcion_6 INT,
    opcion_7 INT,
    opcion_5_detalle VARCHAR(100),
    opcion_6_detalle VARCHAR(100),
    opcion_7_detalle VARCHAR(100),
    area_trabajo VARCHAR(50),
    sugerencias_programa_formativo VARCHAR(100),
    evaluacion_final BOOLEAN NOT NULL,
    Id_cuaderno INT NOT NULL,
    dni_alumno VARCHAR(10) NOT NULL,
    FOREIGN KEY (dni_alumno) REFERENCES ALUMNO(DNI),
    FOREIGN KEY (Id_cuaderno) REFERENCES CUADERNO_TUTOR(Id_cuaderno),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE VALORACION_ALUMNO (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    opcion_1 INT NOT NULL,
    opcion_2 INT NOT NULL,
    opcion_3 INT NOT NULL,
    opcion_4 INT NOT NULL,
    opcion_5 INT NOT NULL,
    opcion_6 INT NOT NULL,
    opcion_7 INT NOT NULL,
    opcion_8 INT NOT NULL,
    aspectos_destacables VARCHAR(100),
    aspectos_mejorables VARCHAR(100),
    Id_cuaderno INT NOT NULL,
    dni_alumno VARCHAR(10) NOT NULL,
    FOREIGN KEY (dni_alumno) REFERENCES ALUMNO(DNI),
    FOREIGN KEY (Id_cuaderno) REFERENCES CUADERNO_TUTOR(Id_cuaderno),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE TIENE (
    DNI_alumno VARCHAR(10) NOT NULL,
    Id_cuaderno INT NOT NULL,
    FOREIGN KEY (DNI_alumno) REFERENCES ALUMNO(DNI),
    FOREIGN KEY (Id_cuaderno) REFERENCES CUADERNO_TUTOR(Id_cuaderno),
    PRIMARY KEY (DNI_alumno, Id_cuaderno),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SUPERVISA (
    DNI_alumno VARCHAR(10) NOT NULL,
    DNI_tutor_laboral VARCHAR(10) NOT NULL,
    FOREIGN KEY (DNI_alumno) REFERENCES ALUMNO(DNI),
    FOREIGN KEY (DNI_tutor_laboral) REFERENCES TUTOR_LABORAL(DNI),
    PRIMARY KEY (DNI_alumno, DNI_tutor_laboral),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE VISITA (
    Id_visita INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    num_visita INT NOT NULL,
    Fecha DATE NOT NULL,
    Incidencia VARCHAR(500) NOT NULL,
    Observaciones VARCHAR(100),
    Id_cuaderno INT NOT NULL,
    FOREIGN KEY (Id_cuaderno) REFERENCES CUADERNO_TUTOR(Id_cuaderno),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);